language: node_js
node_js:
  - 10
  - 10.16.3
  - 12
  - 13
cache:
  npm: false
sudo: false
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install
script:
  - pnpm t
notifications:
  email: false
